# Example user configuration for A5C Runner
# This file overrides settings from the built-in default configuration
# Uncomment and modify the sections you want to customize

# Override default settings
# defaults:
#   cli_command: "myagent --model gpt-4 --message {{prompt}}"
#   model: "claude-3-opus-20240229"
#   max_turns: 25
#   timeout: 45

# Override MCP configuration path
# mcp_config_path: ".a5c/custom-mcps.json"

# Override file processing settings
# file_processing:
#   include_patterns:
#     - "src/**/*.ts"
#     - "lib/**/*.js"
#     - "**/*.md"
#   exclude_patterns:
#     - "node_modules/**"
#     - "dist/**"
#     - "*.test.*"

# Enable and configure remote agents (optional)
remote_agents:
  enabled: true
  cache_timeout: 120  # 2 hours
  retry_attempts: 5
  retry_delay: 2000   # 2 seconds
  sources:
    individual:
      # development agents
      - uri: "https://raw.githubusercontent.com/a5c-ai/registry/main/agents/development/developer-agent.agent.md"
        alias: "developer-agent"
      - uri: "https://raw.githubusercontent.com/a5c-ai/registry/main/agents/development/validator-agent.agent.md"
        alias: "validator-agent"
      # news agents
      - uri: "https://raw.githubusercontent.com/a5c-ai/registry/main/agents/news/news-aggregator-agent.agent.md"
        alias: "news-aggregator-agent"
      - uri: "https://raw.githubusercontent.com/a5c-ai/registry/main/agents/news/project-news-analyzer-agent.agent.md"
        alias: "project-news-analyzer-agent"
      # media agents
      - uri: "https://raw.githubusercontent.com/a5c-ai/registry/main/agents/media/video-generation-agent.agent.md"
        alias: "video-generation-agent"
      - uri: "https://raw.githubusercontent.com/a5c-ai/registry/main/agents/media/video-editing-agent.agent.md"
        alias: "video-editing-agent"
      - uri: "https://raw.githubusercontent.com/a5c-ai/registry/main/agents/media/image-generation-agent.agent.md"
        alias: "image-generation-agent"
      - uri: "https://raw.githubusercontent.com/a5c-ai/registry/main/agents/media/image-editing-agent.agent.md"
        alias: "image-editing-agent"
      - uri: "https://raw.githubusercontent.com/a5c-ai/registry/main/agents/media/music-generation-agent.agent.md"
        alias: "music-generation-agent"
      - uri: "https://raw.githubusercontent.com/a5c-ai/registry/main/agents/media/speech-generation-agent.agent.md"
        alias: "speech-generation-agent"
    # repositories:
    #   - uri: "https://github.com/a5c-ai/registry/main/agents"
    #     pattern: ".a5c/agents/**/*.agent.md"

# Override agent discovery settings
# agent_discovery:
#   enabled: true
#   max_agents_in_context: 15
#   include_same_directory: true

# Override prompt URI settings
# prompt_uri:
#   cache_timeout: 120
#   retry_attempts: 5
#   retry_delay: 2000 