# Example user configuration for A5C Runner
# This file overrides settings from the built-in default configuration
# Uncomment and modify the sections you want to customize

# Override default settings
defaults:
  cli_command: "printenv | cat - {{prompt_path}} | COLORBT_SHOW_HIDDEN=1 RUST_BACKTRACE=full CODEX_QUIET_MODE=1 codex exec --dangerously-bypass-approvals-and-sandbox -c model=codex-mini -c model_provider=azure -c model_providers.azure.name=azure -c model_providers.azure.wire_api=responses -c model_providers.azure.base_url=https://{{envs.AZURE_OPENAI_PROJECT_NAME}}.openai.azure.com/openai -c model_providers.azure.env_key=AZURE_OPENAI_API_KEY -c model_providers.azure.query_params.api-version=2025-04-01-preview --output-last-message /tmp/agent-output.md"


# Override MCP configuration path
# mcp_config_path: ".a5c/custom-mcps.json"

# Override file processing settings
# file_processing:
#   include_patterns:
#     - "src/**/*.ts"
#     - "lib/**/*.js"
#     - "**/*.md"
#   exclude_patterns:
#     - "node_modules/**"
#     - "dist/**"
#     - "*.test.*"
remote_agents:
  enabled: true
  cache_timeout: 120  # 2 hours
  retry_attempts: 5
  retry_delay: 2000   # 2 seconds
  sources:
    individual:
      - uri: "https://raw.githubusercontent.com/a5c-ai/registry/main/agents/development/developer-agent.agent.md"
        alias: "developer-agent"
      - uri: "https://raw.githubusercontent.com/a5c-ai/registry/main/agents/news/news-aggregator-agent.agent.md"
        alias: "news-aggregator-agent"
      - uri: "https://raw.githubusercontent.com/a5c-ai/registry/main/agents/news/project-news-analyzer-agent.agent.md"
        alias: "project-news-analyzer-agent"
      - uri: "https://raw.githubusercontent.com/a5c-ai/registry/main/agents/development/recruiter-agent.agent.md"
        alias: "recruiter-agent"
      - uri: "https://raw.githubusercontent.com/a5c-ai/registry/main/agents/development/validator-agent.agent.md"
        alias: "validator-agent"
      - uri: "https://raw.githubusercontent.com/a5c-ai/registry/main/agents/communication/researcher-base-agent.agent.md"
        alias: "researcher-base-agent"
      - uri: "https://raw.githubusercontent.com/a5c-ai/registry/main/agents/communication/discord-manager-agent.agent.md"
        alias: "discord-manager-agent"
      - uri: "https://raw.githubusercontent.com/a5c-ai/registry/main/agents/communication/slack-manager-agent.agent.md"
        alias: "slack-manager-agent"
      - uri: "https://raw.githubusercontent.com/a5c-ai/registry/main/agents/development/build-fixer-agent.agent.md"
        alias: "build-fixer-agent"


# Override agent discovery settings
# agent_discovery:
#   enabled: true
#   max_agents_in_context: 15
#   include_same_directory: true

# Override prompt URI settings
# prompt_uri:
#   cache_timeout: 120
#   retry_attempts: 5
#   retry_delay: 2000 
